### PR TITLE
Tweak conversation list layout

### PR DESCRIPTION
**Pull request by mateoeh**
// FREEBIE

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * OnePlus 3T, Android 7.1.1
 * AVD, Android 7.1.1
 * AVD, Android 4.4.2
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

----------

### Description

Adjusts conversation list layout to more closely fit [material design specifications](https://material.io/guidelines/components/lists.html#lists-specs):

* 16dp padding on both sides
* Avatar should be 40x40dp
* Text should be 72dp from left edge
* List item should be 72dp tall
* Should align to 8dp baseline grid

For reference:

md-list-spec

Screenshots:

|Before|After|Layout bounds|
|--|--|--|
|before|after|after-layout|

Related: #6114

### CODE REVIEW

**Comment by moxie0** [comment]
I'm happy with the current conversation list layout in terms of avatar icon size, position, primary and secondary size and position. I'm flexible on right margin and FAB.

What we're doing right now is consistent with other messengers, I think the material design specs would be more appropriate for the contact selection activity.

**Comment by mateoeh** [comment]
From what I can tell, there's just as many messengers that follow material design guidelines (Android Messages, Skype, Allo/Duo, Facebook Messenger, and Hangouts) as ones that don't (e.g. WhatsApp, Textra, and Telegram). Consistency with Google's system apps (Gmail, Contacts, Google Play) is important as well, and as time goes on more and more apps are switching to material design.

In terms of avatar size, perhaps we could reach a middle ground at 48x48dp? As it stands, it just seems unwieldly large.

**Comment by RiseT** [comment]
Imho, one should have a good reason for straying away from guidelines. "Others do it" is hardly one to me.

**Comment by moxie0** [comment]
Thanks for looking into this, but I actually just made them larger in order to match what people consider popular. I think it looks better myself, so for now I'm going to leave it as-is.

**Pull request closed without merging**
