### PR TITLE
Added Samsung multi window support

### PR DESCRIPTION
**Pull request by aigna**
### First time contributor checklist

- [ x] I have read [how to contribute](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [ x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x ] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x ] I have tested my contribution on these devices:
 * Samsung Galaxy Note 5 (N920W8) Android 6.0.1
- [x] My contribution is fully baked and ready to be merged as is
- [x ] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

//FREEBIE
----------

### Description
Added the support for Samsung multi window. Just added the necessary options in the AndroidManifest.xml file.

### CODE REVIEW

**Comment by haffenloher** [comment]
Unfortunately, putting `FREEBIE` in your PR description has no effect. It has to be included in the commit message of your first commit instead.

**Comment by aigna** [comment]
Fixed. Thanks :)

**Comment by moxie0** [comment]
Thanks, can you link to some info on what samsung multi-window support is, and maybe post some screenshots with this change?  Thanks!

**Comment by aigna** [comment]
It's the equivalent of the Android N split screen, but only for Samsung devices (it works also with Android Lollipop and Marshmallow). In that way, users can open Signal with another application at the same time.

screenshot

**Comment by moxie0** [comment]
in 3.20.0

**Pull request closed without merging**
