### PR TITLE
Change app icon

### PR DESCRIPTION
**Pull request by iadmir**
### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Nexus 4, Android 5.1
 * Virtual device Nexus 5X, Android 7.1.1
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

----------

### Description
Fixes: #5936 

screenshot_1486556220
screenshot_1486308900

### CODE REVIEW

**Comment by jrmswell** [comment]
I find it strange that there are two different logos for Signal, is there reason for this?

**Comment by Pazuu** [comment]
Well this is a PR to change this :o) 
But if you have questions or want to discuss something you are very welcome in the community forum (https://whispersystems.discoursehosting.net/)

**Comment by sweeper3000** [comment]
@jrmswell if you're referring to the the shape of the two different logos, the pixel launcher the round version if available.

**Comment by jrmswell** [comment]
@sweeper3000 No, I'm referring to the logo design itself. On android the logo currently [looks like this](https://lh5.ggpht.com/jKZCC5NR0uU01scYefDjUICueE59pEpamDz3J3LDAg3X-6DupmpsDysbFUc8WUFDgfk) whilst on iOS and the chrome web store it [looks like this](https://lh3.googleusercontent.com/J083a8SPxwktUdtqVnO9xUSjlbyMrUhn_cNTEoRm19jVuNmfQled6OkyuUi3UCe3Q06NDnJyyI8).

It's just a weird continuity thing, that was all

**Comment by jeremymasters** [comment]
@jrmswell That's what this PR is all about is consolidating the logo.

**Comment by Lokesh-Krishna** [comment]
Is there any reason that the round icon cannot be used as the regular icon as well? It just looks better than the other one where it looks like the icon was pasted into a square.
The icon in the circle seems to fit better.

**Comment by piratenpanda** [comment]
To my eyes it's exactly the opposite because the icon is not a circle so it looks kinda out of place on the circular background. All this round icon hype the pixel started is  beyond me anyway, but this is not a discussion forum so sry for the noise

**Comment by moxie0** [comment]
I tried running this on a Nexus 5 and the launcher icon is too small, looks like maybe the density resources are incorrect?

**Comment by iadmir** [comment]
Seems that this is a known "issue" with Android icon generator inside Android Studio:
http://stackoverflow.com/questions/32231439/app-icon-on-device-is-too-small

Fixed, please test it now.

screenshot_1487327314

**Comment by snaggen** [comment]
Just from looking at the tab "Files Changed" for this PR it seems like some icons have a lot of padding compared to the previous.
Icons I noticed at a quick glance:
* artwork/logo-512.png 
* icon_dialog.png icons
* lockscreen_watermark_dark.png

Not sure if this is an issue or if it was done intentionally, but it might be something to look at.

**Comment by p4nci** [comment]
@snaggen no, imo that's fine. For details see material design guidelines:
https://material.io/guidelines/style/icons.html
particularly content area:
The content of an icon should remain inside of the live area. ([grid live area graphic](https://storage.googleapis.com/material-design/publish/material_v_10/assets/0Bx4BSt6jniD7X2dma3g0Z3lZRG8/style_icons_system_grid_area_live.png))

**Comment by moxie0** [comment]
I think we also need a version with a transparent background. When the app starts for the first time, it currently displays the Signal icon on a screen with a white background while it initializes. I think that screen should have a solid "signal blue" background now, with the Signal icon on top of it. If we use the current icon.png resource, it looks strange because it has its own background.

**Comment by iadmir** [comment]
Icons with transparent background added.

**Comment by moxie0** [comment]
in 3.32.0 thanks for all the work!

**Comment by sabret00the** [comment]
I'm really not a fan of this new icon. I've tried to let it grow on me but it's just not a great icon.

**Pull request closed without merging**
