### PR TITLE
enable media forwarding

### LINKED ISSUE #1362: [bug] Forwarding media messages only forwards text
Sharing pictures from the gallery or anywhere else works great in 2.0.7., but whenever I want to forward a message with an image, only the text gets transferred into the new message.

Observed behaviour: Forwarding messages with pictures only forwards the text.
Expected behaviour: Forwarding messages with pictures forwards the whole message.

@McLoo identified the problem in ConversationFragment.java (https://github.com/WhisperSystems/TextSecure/issues/316#issuecomment-40311690):

```java
  private void handleForwardMessage(MessageRecord message) {
    Intent composeIntent = new Intent(getActivity(), ShareActivity.class);
    composeIntent.putExtra(ConversationActivity.DRAFT_TEXT_EXTRA, message.getDisplayBody().toString());
    composeIntent.putExtra(ShareActivity.MASTER_SECRET_EXTRA, masterSecret);
    startActivity(composeIntent);
  }
```

### PR DESCRIPTION
**Pull request by mcginty**
fixes #1362

### CODE REVIEW

**Comment by McLoo** [comment]
not working for me

forwarding image, 
log is 
from clicking "forward"
to "Share with" screen

```
11-19 01:09:09.183 6462-6462/org.thoughtcrime.securesms I/Timeline: Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:759158
11-19 01:09:09.214 6462-6462/org.thoughtcrime.securesms W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
11-19 01:09:09.214 6462-6462/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onPause()
11-19 01:09:09.257 6462-6462/org.thoughtcrime.securesms W/ThumbnailView: Not re-loading slide content://org.thoughtcrime.securesms/part/1447891545408/309
11-19 01:09:09.263 6462-6462/org.thoughtcrime.securesms W/ThumbnailView: Not re-loading slide content://org.thoughtcrime.securesms/part/1447891545599/310
11-19 01:09:09.298 6462-6462/org.thoughtcrime.securesms W/KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
11-19 01:09:09.298 6462-6462/org.thoughtcrime.securesms W/KeyCachingService: Decrementing activity count...
11-19 01:09:09.298 6462-6462/org.thoughtcrime.securesms W/KeyCachingService: Starting timeout: 22920000
11-19 01:09:09.303 6462-6462/org.thoughtcrime.securesms W/MessageRetrievalService: Active Count: 0
11-19 01:09:09.311 6462-6462/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onCreate(null)
11-19 01:09:09.316 6462-6462/org.thoughtcrime.securesms W/ExperienceUpgradeActivity: getExperienceUpgrade(157)
11-19 01:09:09.318 6462-6462/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
11-19 01:09:09.335 6462-6462/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
11-19 01:09:09.379 6462-6899/org.thoughtcrime.securesms E/ActivityThread: Failed to find provider info for org.thoughtcrime.securesms
11-19 01:09:09.380 6462-6899/org.thoughtcrime.securesms W/ShareActivity: java.io.FileNotFoundException: No content provider: content://org.thoughtcrime.securesms/part/1447891545408/309
11-19 01:09:09.380 6462-6899/org.thoughtcrime.securesms W/ShareActivity:     at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1066)
11-19 01:09:09.380 6462-6899/org.thoughtcrime.securesms W/ShareActivity:     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:921)
11-19 01:09:09.380 6462-6899/org.thoughtcrime.securesms W/ShareActivity:     at android.content.ContentResolver.openInputStream(ContentResolver.java:646)
11-19 01:09:09.380 6462-6899/org.thoughtcrime.securesms W/ShareActivity:     at org.thoughtcrime.securesms.ShareActivity$1.doInBackground(ShareActivity.java:122)
11-19 01:09:09.380 6462-6899/org.thoughtcrime.securesms W/ShareActivity:     at org.thoughtcrime.securesms.ShareActivity$1.doInBackground(ShareActivity.java:114)
11-19 01:09:09.380 6462-6899/org.thoughtcrime.securesms W/ShareActivity:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
11-19 01:09:09.380 6462-6899/org.thoughtcrime.securesms W/ShareActivity:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-19 01:09:09.380 6462-6899/org.thoughtcrime.securesms W/ShareActivity:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
11-19 01:09:09.380 6462-6899/org.thoughtcrime.securesms W/ShareActivity:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-19 01:09:09.380 6462-6899/org.thoughtcrime.securesms W/ShareActivity:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-19 01:09:09.380 6462-6899/org.thoughtcrime.securesms W/ShareActivity:     at java.lang.Thread.run(Thread.java:818)
11-19 01:09:09.388 6462-6462/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onResume()
11-19 01:09:09.494 6462-6462/org.thoughtcrime.securesms W/KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
11-19 01:09:09.494 6462-6462/org.thoughtcrime.securesms W/KeyCachingService: Incrementing activity count...
11-19 01:09:09.523 6462-6462/org.thoughtcrime.securesms W/MessageRetrievalService: Active Count: 1
11-19 01:09:09.699 6462-6462/org.thoughtcrime.securesms I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1c841c08 time:759674
11-19 01:09:17.871 6462-7677/org.thoughtcrime.securesms W/WebSocketConnection: Sending keep alive...
11-19 01:09:17.989 6462-7676/org.thoughtcrime.securesms W/OkHttpClientWrapper: onMessage: BINARY
11-19 01:09:17.989 6462-7676/org.thoughtcrime.securesms W/WebSocketConnection: WSC onMessage()
11-19 01:09:17.989 6462-7676/org.thoughtcrime.securesms W/WebSocketConnection: Message Type: 2
11-19 01:09:22.209 6462-6900/org.thoughtcrime.securesms W/MessageRetrievalService: Application level read timeout...
11-19 01:09:22.212 6462-6900/org.thoughtcrime.securesms W/MessageRetrievalService: Network requirement: true, active activities: 1, push pending: 0
11-19 01:09:22.218 6462-6900/org.thoughtcrime.securesms W/MessageRetrievalService: Reading message...
```

**Comment by mcginty** [comment]
you sure you're in sync with my branch? can't repro it not working against this diff

**Comment by McLoo** [comment]
Checked out the fix branch 
Will double check though

**Comment by McLoo** [comment]
should have double checked before whining.
Works  95%. See: #4599

**Comment by moxie0** [comment]
can you rebase this onto master?

**Pull request closed without merging**
