### PR TITLE
Enable preview for image drafts

### PR DESCRIPTION
**Pull request by McLoo**
This is pretty cool in three ways:
1. you can (p)review and save your TS-photographs (*Edit:in full resolution*)
2. you can (p)review (and save) your gallery picked images
3. McLoo is happy having this feature now

Could also be useful if somewhere in the future we have in app audio or video recording...

### CODE REVIEW

**Comment by rhodey** [comment]
tested manually on my GB device and a 4.1.2 LG device, lgtm.

**Comment by McLoo** [comment]
rebased

**Comment by mcginty** [comment]
needs to be rebased again, doesn't work currently

**Comment by moxie0** [comment]
closing for lack of activity, @McLoo sorry we dragged this one out, definitely reopen if you get it rebased and working again

**Pull request closed without merging**
