### PR TITLE
Disable send button during attachment drawer clear animation

### PR DESCRIPTION
**Pull request by haffenloher**
This is a proposed fix for #3843.

### CODE REVIEW

**Comment by brumsoel** [comment]
Rebased.

**Comment by brumsoel** [comment]
Rebased

**Comment by brumsoel** [comment]
Rebased & tested.

**Comment by mcginty** [comment]
I'd prefer for the AttachmentManager not to know about the send button. I just opened #4571 as an alternative solution (just remove the reference to the slide before the animation completes), so going to close this one.

Thanks for your proposal!

**Pull request closed without merging**
