### PR TITLE
Tint and resize import/export icons

### PR DESCRIPTION
**Pull request by mateoeh**
// FREEBIE

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * OnePlus 3T, Android 7.1.1
 * AVD, Android 7.1.1
 * AVD, Android 4.4.2
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

----------

### Description

import-export

Adds blue tint to icons when using light theme + resizes to 24dp

### CODE REVIEW

**Comment by RiseT** [comment]
As an aside, the icons of this view are sized bigger than the ones of the settings view (not because of this PR).  Shouldn't they have one standardized size?

**Comment by mateoeh** [comment]
Good point.

import-export

**Comment by mateoeh** [comment]
Fixed merge conflicts

**Comment by mateoeh** [comment]
Closing and rebasing

**Pull request closed without merging**
