### PR TITLE
let the quick camera remember front/back mode

### LINKED ISSUE #4438: Wishlist: please let the quick camera remember the last used mode (front/rear)
I see that with 8fd0ea3 the quick picture mode uses the front facing camera by default. I personally don't like it, but if you think that for most people it's more "useful" like this, then fine.

I suggest to make Signal remember the last used camera (either per-conversation or application-wide). This would make most people happy and I think it fits within your development guidelines (don't add settings, ...).

### PR DESCRIPTION
**Pull request by agrajaghh**
fixes #4438

//FREEBIE

### CODE REVIEW

**Comment by mcginty** [comment]
Any reason not to just have a `getDirectCaptureCameraId()` and set/get the camera id if `isMultiCamera()` is true? It reads a little weird to have a isRearCamera in CameraView and isFront in prefs.

**Comment by agrajaghh** [comment]
nope, changed it to `getDirectCaptureCameraId()` :wink:

**Comment by mcginty** [comment]
holding off since the CameraView changes due to galaxy nexus having weird orientation issues that I haven't been able to reproduce.

**Comment by agrajaghh** [comment]
@mcginty was https://github.com/WhisperSystems/Signal-Android/commit/b0137c08cbd31507a367cab042f071df5630815a just temporary? or should I rebase now?

**Comment by mcginty** [comment]
pending merge of https://github.com/WhisperSystems/Signal-Android/pull/4529

**Comment by mcginty** [comment]
tested, looks good :). in 3.5.0

**Pull request closed without merging**
