### PR TITLE
Support for stickers and scribbles

### PR DESCRIPTION
**Pull request by moxie0**

### CODE REVIEW

**Comment by 2-4601** [comment]
Fixes #5445.

Is this still WIP? Tried this but I can't find where to browse the stickers or how to activate the scribble mode?
drawer

**Comment by moxie0** [comment]
@2-4601 If you "attach" an image, there should be a little "edit" pencil in the bottom right corner that you can tap on. That takes you to an activity you can add stickers, text, and draw on.

**Comment by 2-4601** [comment]
Oh, I see it now.

#### A bug with the pencil color display:
1. Open scribble mode
1. Tap the text input icon (Tt) and notice that the color is red
1. Keyboard opens, dismiss it with the back button
1. Tap the brush icon (notice that the first tap doesn't select it but the color of the status bar changes?)
1. Tap the brush icon again (it gets selected now) and notice that the color is red
1. Change the color from the color slider to purple

**Actual result:** The pencil icon is still red
**Expected result:** The pencil icon should be purple

**Comment by moxie0** [comment]
@2-4601 good catches! should be fixed

**Comment by FeuRenard** [comment]
Yes, fixed: brush icon shows color change & brush icon doesn't have to be hit twice.

On my real device (3.5 inch display) the color slider is sometimes hard to hit with my finger. Works 90% fine after some practice :wink:.

**Comment by 2-4601** [comment]
The brush color switching issue is solved for me now too. :+1: 

This latest commit introduced something strange. Now every time I start the scribble mode the keyboard is open by default. When I switch back to a build without this latest commit the keyboard is not open when the scribble mode starts. This happens only with my Nvidia K1 6.0.1 device. On my 5.1.1 Lollipop device the keyboard is never open by default. I'm using the Google keyboards on both devices.

One feature I would like to see is white in the color slider. I've been drawing stuff and I really miss that there's no white color. From UX point of view I would expect it to be at the bottom of the slider because black is on top.

**Comment by moxie0** [comment]
@2-4601 Thanks I'll look into the keyboard thing, think I know what to do.  

To include white, we'd have to change the "text" and "brush" (and "emoji" for consistency) icons to have a slight drop shadow or outline. Otherwise it'd be white on white. 

There's no way to tint drawables like that (that I know of), so we'd need to create modified versions of the actual png actual assets.  I'm afraid I might not have it in me at the moment, but if someone with photoshop skills does it and submits a PR against this branch I'll add white.  =)

**Comment by moxie0** [comment]
@2-4601 Can you test that most recent change and see if the keyboard is still open on that device by default?

**Comment by 2-4601** [comment]
The keyboard issue is fixed now :+1: 

I see adding white isn't as simple as I thought. Well, I'll just have to settle for light yellow to draw snow for now. I hope it doesn't look too much like piss :D

**Comment by moxie0** [comment]
@2-4601 there's a snowflake sticker!

**Comment by moxie0** [comment]
in 3.25.0

**Pull request closed without merging**
