### PR TITLE
Resize group images

### LINKED ISSUE #5461: Group Images are still not getting resized.
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Sending a large Image (f.i. 13MPixel, ~6MB .jpg) to a Group doesn't resize the Image to a lower dimension and filesize. When you send the same Image to a single Contact in contrary, it -does- resize the image.

This leads to a large amount of traffic use on both ends. Group images should ideally be handled the same way as single contact images.
In a perfect version, the user should be asked for whether it should resize the image or not.

This issue has actually been found and fixed 1 year ago here **BUT** it is still happening in the latest Version of Signal: [https://github.com/WhisperSystems/Signal-Android/issues/2913](https://github.com/WhisperSystems/Signal-Android/issues/2913)

### Steps to reproduce
- create a group, add one or more contacts.
- send a large image (13 MPixel / ~ 6 MB) to this group. 

**Actual result:** The Image is not getting resized and Signal sends a whole 6 MB image to the group. The group receives (and has to download) a full 6 MB Image.
**Expected result:** You actually send a resized image (1280 * xxxx, ~200 KB) to that group. The group receives and downloads just a 200 KB Image.

### Device info

**Device:** LG G3
**Android version:** 6.0.1
**Signal version:** 3.15.2

### PR DESCRIPTION
**Pull request by FeuRenard**
### First time contributor checklist
- [x] I have read [how to contribute](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist
- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Sony Xperia U, Android 4.4.4 (CyanogenMod)
- [x] My contribution is fully baked and ready to be merged as is
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in my commit message

----------

### Description

Fixes #5461

Unfortunately I was not able to test this with my Android 6.0 running virtual device. I did not manage to download a large image with the browser. It always crashes. Maybe the virtual device has some storage limitations.

// FREEBIE

### CODE REVIEW

**Comment by moxie0** [comment]
Thanks for looking into this but I can't really engage with a PR that hasn't yet been tested. Will wait and see if anyone else can try.

**Comment by 2-4601** [comment]
Tested these changes on top of master (3.17.0)
- Nexus 4 (2 GB RAM),  Android 6.0.1
- Huawei U8800 (512 MB RAM), Android 4.0.4

With [this](https://seanchase.files.wordpress.com/2012/01/the-crystal-ball-waterhouse-1902.jpg) 3.88 MB JPEG image:
* Nexus 4 transforms it to a 206 KB JPEG
* Huawei transforms it to a 75 KB JPEG

**Comment by 2-4601** [comment]
And [this](https://commons.wikimedia.org/wiki/File:In_the_Conservatory.jpg) **173 MB** JPEG image:
* Nexus 4 transforms it to a 246 KB JPEG (took 2 minutes)
* Huawei transforms it to a 99 KB JPEG (took 5 minutes)

No crashing, just takes some time to process it:+1:

**Comment by moxie0** [comment]
The @2-4601 seal of approval. Just needs to be rebased and it'll be good to go.

**Comment by moxie0** [comment]
(rebased onto 3.18.0)

**Comment by FeuRenard** [comment]
Rebased onto your 3.18.0 branch.

**Comment by moxie0** [comment]
in 3.18.0

**Pull request closed without merging**
