### PR TITLE
update camera preview strategy

### PR DESCRIPTION
**Pull request by mcginty**
@McLoo @2-4601 would you mind trying this branch out to see if it alleviates some of the problems you saw?

### CODE REVIEW

**Comment by 2-4601** [comment]
Sure.
* Quickcapture still sometimes hangs (on a still shot) at start but then proceeds if I tap the screen or make the mode full screen.
* Device provisioning camera works now! (But it also has that hanging issue sometimes at start)

**Comment by mcginty** [comment]
@2-4601 thanks so much for the live action testing

I just updated this branch with an attempt to stop this hanging you're describing.

**Comment by 2-4601** [comment]
Ok, will test in a bit. Just re-tested with 3.4.2 to make sure it has worked before. The answer is yes. There's some quick stuttering at the beginning even there but it never gets stuck on a still frame.

**Comment by mcginty** [comment]
Thanksthanks

Yeah, it will be near-impossible to remove all stuttering because some of it seems to happen internally by Android when spinning up the Camera on some devices (regardless of if we call the initializers off the main thread).

**Comment by 2-4601** [comment]
I see you have done some more while I was testing but results based on https://github.com/mcginty/TextSecure/commit/036e89f922cca7fe48389421525a09bef9737291
* I think it got stuck but maybe 1/50 times. I tested so many times that it's also possible that my brain hanged instead of the quick camera. At the end I was not able to make it hang at all.
* The very first time I tried the QR camera it definitely hanged on a still pic. But after that it never got stuck.

**Comment by 2-4601** [comment]
Ok, with the latest commit the camera _"has become unstuck in time."_ I.e. I can't get it to hang anymore.

**Comment by moxie0** [comment]
in master

**Pull request closed without merging**
