### PR TITLE
Add MediaOverview link to MediaPreview

### PR DESCRIPTION
**Pull request by FeuRenard**
### Contributor checklist
- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
  - AVD Nexus 5X, Android 5.1
  - Sony Xperia U, Android 4.4.4 (CyanogenMod) [EDIT, 21 Sep 16]
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

---
### Description

This PR adds a button to the media preview. It links to the media gallery (all images) of the recipient.
### Screenshots

bildschirmfoto von 2016-09-20 20-24-14
bildschirmfoto von 2016-09-20 20-24-17

// FREEBIE

### CODE REVIEW

**Comment by FeuRenard** [comment]
I did not know about [image draft previews](https://github.com/WhisperSystems/Signal-Android/commit/e79ee7803fea85ec999e0f6dc803fc1227096cd0) so far.
I have to close this PR since this use case is not implemented/tested yet.

**Comment by moxie0** [comment]
Sorry I don't think I understand what this is for. Can you restate what problem you're trying to solve? Thanks!

**Comment by FeuRenard** [comment]
There are two cases in which you can use this:

1. Enter MediaPreview (Conversation -> select image). The proposed button allows to enter MediaOverview directly from this activity. At the moment you have to go back to the conversation (1st click), open menu (2nd click) and choose "All images" (3rd click) to do the same thing.

2. Enter MediaOverview (Conversation -> menu -> All images) and from there enter MediaPreview (MediaOverview -> select an image). The proposed button allows to reenter MediaOverview. In this case the new button is redundant as you could also use the back button.

And – although this is not always an argument: WhatsApp and Threema offer this button, too :wink: (even as the first menu item in image preview).

### Screenshots
Threema
screenshot_2016-11-12-11-48-32
WhatsApp
screenshot_2016-11-12-11-49-22

**Comment by FeuRenard** [comment]
Rebased.
After this PR there would be three buttons. On small screens the space for the activity's title is limited. Therefore we shouldn't show all buttons all the time. Instead some or all of them should be marked with `app:showAsAction=ifRoom`. The decision which buttons should be shown in which order is up to you.

**Comment by moxie0** [comment]
in 3.24.0

**Pull request closed without merging**
