### PR TITLE
Update lock notification icons, take II

### PR DESCRIPTION
**Pull request by passy**
This re-opens #5284.

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Nexus 5, Android 6.0.1
- [x] My contribution is fully baked and ready to be merged as is
- [x] I have made the choice whether I want the Bithub reward or not by omitting or adding the word `FREEBIE` in my commit message

----------

The lock icons displays in the "cached passphrase" notification currently have two issues:

- They lack high-res versions and look rather blurry on high-DPI phones.
- They have a very different shape even though they're part of the same notification. For example, one of them contains a keyhole, the other one doesn't.

Here's a proposal for unifying the look somewhat and upgrading the resolution at the same time.

<table>
<tr>
<td>

</td>
<td>

</td>
</tr>
<tr>
<td><b>Old Look</b></td>
<td><b>New Look</b></td>
</tr>
</table>

The icons I've added are the official [Material Icons](https://design.google.com/icons/) which are available under a [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) license.

The new `ic_menu_lock_dark` icon is 24dp in the real icon size, including a padding which makes it 32dp in total.

The notification balloon icon `icon_cached` is available in a v11 and a pre-v11 version as generated by the Asset Studio. The v11 version is white, 24dp full icon size with 1dp padding, so 22dp in real icon size. I've removed the explicit `-v9` versions as we now have full fallbacks available.

Apologies again for the mess that the previous attempt for this was. It'll be a lesson to me to not open PRs while germs are taking over my brain.

[Review on Reviewable](https://reviewable.io/reviews/whispersystems/signal-android/5325)

### CODE REVIEW

**Comment by moxie0** [comment]
@agrajaghh this look good to you?

**Comment by agrajaghh** [comment]
@moxie0 yep looks good!

But I couldn't test this on my gingerbread device: :disappointed: 
`LinearAlloc exceeded capacity (5242880), last=3536`

**Comment by moxie0** [comment]
@agrajaghh dang, has that been happening for you for a while or did a recent change push you over?

**Comment by agrajaghh** [comment]
@moxie0 just did git bisect:

08e2221dc0ce4cff5cff78b3b28a42059ecf934c 

```
08e2221dc0ce4cff5cff78b3b28a42059ecf934c is the first bad commit
commit 08e2221dc0ce4cff5cff78b3b28a42059ecf934c
Author: Moxie Marlinspike <moxie@thoughtcrime.org>
Date:   Fri Feb 19 17:07:41 2016 -0800

    Support for synchronizing read state to/from desktop

    // FREEBIE
```

**Comment by moxie0** [comment]
@agrajaghh ok how about how?

**Comment by agrajaghh** [comment]
@moxie0 tested this branch rebased on master at  8c8cd413597d5b6da105f759eaa5d4744f55fada on a HTC desire 2.3.7

working, and icons are looking good too :+1:

**Pull request closed without merging**
