### PR TITLE
automatically check verification status when succeeding a qrcode scan

### PR DESCRIPTION
**Pull request by Trolldemorted**
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Redmi Note 3 Pro, Android 7
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

----------

### Description

When succeeding a scan, the contact should be marked verified automatically.

### CODE REVIEW

**Comment by nrizzio** [comment]
Does this synchronize the verified state with other linked devices (and save it in the local database too)?

**Comment by Trolldemorted** [comment]
i have no 2nd Android device at hand to test whether it is actually saved on Android, but i am pretty sure all sibling devices receive a sync message with the verification status.

E.g. my signal-cli master device outputs this:
```
Envelope from: ?MYSELF? +49XXXXXXX462 (device: 9)
Timestamp: 1497386110026 (2017-06-13T20:35:10.026Z)
Received a sync message
Received sync message with verified identities:
 - +49SCANNEDCONTACT289: VERIFIED
   xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx
```
for each contact i verify by scanning.

**Comment by moxie0** [comment]
Thanks @Trolldemorted but I made the decision not to do this. A single QR scan is confirmation for both devices, but this would only have the effect of verifying a single device. I'd prefer to avoid confusion that manual action is required on the second device by not introducing automation. I did consider a tooltip or toast, but am leaving it for now.

**Comment by jbaker6953** [comment]
What information is communicated to the user manually toggling the "Verified" switch to the on position that is not communicated by scanning the QR code to switch the "Verified" switch to the on position?

**Pull request closed without merging**
