### PR TITLE
Add date indicator above messages

### PR DESCRIPTION
**Pull request by Omikron43**
This adds the date between two messages when the first message was sent/received at minimum one day before the second message.

The date is translated with respect to the language set in TS but also suffers from #3102.
The year is only displayed when the message was sent/received in a year smaller than the current year.

Screenshots with light and dark theme:
date-sep-light
date-sep-dark

### CODE REVIEW

**Comment by Mihahn** [comment]
Finally! Closes #3147 :smile:

**Comment by Omikron43** [comment]
Ahh searched but didn't find anything. Thanks!

**Comment by heyimgay** [comment]
Would it be possible to change the indicator so it's under the message? I usually have a rough idea of when the message was sent/received and i would like to use the date indicator to help me quickly find the message while scrolling up.

Another ideaI had is making the indicator stay on the screen at the bottom until the next one pushes it out,

**Comment by Omikron43** [comment]
As the messages are listed in chronological order (or rather should be**) from top to bottom for me the separator indicates: now are following all messages that were sent/received on this date.
I also like the floating indicator (like WhatsApp has it). I'm looking into it but I have no idea when I'll find time for it.

** see for example: #3619, #3478, #3312, #2385

**Comment by heyimgay** [comment]
But you always scroll up to find older messages, starting from the most recent message. From bottom to top. Even if you scroll up and go to a different conversation and come back you are returned to the bottom.

**Comment by mcginty** [comment]
Thanks for the PR. I'd need to be convinced the performance impact is minimal before merging this - at first glance of the code it seems like this could cause a decent amount of extra jank.

**Comment by Omikron43** [comment]
I had the same in mind but did not notice more lag than before when quickly scrolling in a large thread.

I also experimented with the [StickyListHeaders](https://github.com/emilsjolander/StickyListHeaders) library that is already used in the contact selection activity. Sadly, the library does not work with ListFragments or RecyclerListeners. Adapting the ConversationFragment (to be a plain Fragment and without the RecyclerListener) did not boost performance.

**Comment by Omikron43** [comment]
Rebased on master and updated for `RecyclerView` using an `ItemDecoration`.
Sadly, I could not get a floating separator to animate properly so I omitted it.

Also I had only the possibility to test on Android 5.1.1 (Nexus 5 and Galaxy S4).

**Comment by grandchild** [comment]
I don't think this is a good idea, at least not in this form. It could be done taking way less space.
I mean you guys usually have a large phone (I do too), but imagine all this on a 4'' display with the keyboard open, there's not much left to read.
Here's what I would like more
textsecure-date-spacer-mockup-slimversion

**Comment by heyimgay** [comment]
maybe make the date only appear while scrolling, and let them 'push' the bottom one off the screen. for this to work we would have to use footers instead of the proposed headers

**Comment by mcginty** [comment]
This would make sense if we removed the date part of the timestamp inside the bubble (similar to how Telegram and WhatsApp do it), and it'd need to be refactored, likely using StickHeaderAdapter to be DRY. @Omikron43 you still around and wanting to experiment with this? If not I'll close for inactivity and we can take another try at it later.

**Comment by mcginty** [comment]
Going to close pending further updates.

**Comment by Omikron43** [comment]
Sorry for the late response, I'm still around and would like to get this (or a similar feature) merged.
The last time I touched the code it was not very performant (with `ItemDecorator`) and I had too less free time to dig further.
If I remember correctly there were some changes to the `ConversationAdapter`. At the weekend I will have another look and see what has to be rebased andif I can improve the performance. Maybe now there are more advanced sticky header techniques for recycler views.

**Pull request closed without merging**
