### PR TITLE
Fixes messages sent to self

### PR DESCRIPTION
**Pull request by Trolldemorted**
### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Nexus 4, Android 6
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

----------

### Description

Messages sent to self are now sent to all linked devices. Credits to gulp21.
Fixes: #4844

// FREEBIE

### CODE REVIEW

**Comment by effigies** [comment]
Looks like this will send to Signal servers even if you don't have linked devices... Does it make more sense to have `sendTextSelf`/`sendMediaSelf` check whether there's a linked device and only perform a normal push if so?

I'm not sure how easy it would be to modify `isSelfSend` to do that check (`TextSecurePrefrences.isMultiDevice`?), but that might be a less intrusive place to check.

(NB: I'm interested in this feature, not in any way associated w/ Signal, so don't mistake my suggestions/thoughts as things that will get this PR accepted.)

**Comment by FeuRenard** [comment]
Related #4147

**Comment by gulp21** [comment]
What happens if the user is not registered for push messages (ie. uses Signal as replacement for the SMS app – I don’t know whether this is a common use case), and sends a message to himself? Sending an SMS message to onself is usually not intended.

(@Trolldemorted Thanks for creating this pull request, I have been busy with other stuff.)

**Comment by Trolldemorted** [comment]
@effigies you are right, checking whether slave devices exist is a good idea imo. I will amend my commit.


@gulp21 does vanilla signal-android support not registering for push messages?

**Pull request closed without merging**
