### PR TITLE
Let LogSubmitActivity adapt to theme

### PR DESCRIPTION
**Pull request by FeuRenard**
### Contributor checklist
- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Sony Xperia U, Android 4.4.4 (CyanogenMod)
 * AVD: Nexus 5X, Android 6.0
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

----------

### Description
Addresses #2625
// FREEBIE

### Screenshots
device-2016-09-04-145741
device-2016-09-04-145825
device-2016-09-04-145805

### CODE REVIEW

**Comment by RiseT** [comment]
URL in the last screenshot should be blue, not torquoise.

**Comment by RiseT** [comment]
By the way - could you make the strings of LogSubmitActivity translatable? Currently they aren't:

- This log will be posted [...]
- Don't submit
- Submit

**Comment by 2-4601** [comment]
@RiseT https://github.com/WhisperSystems/libpastelog/issues/7

**Comment by RiseT** [comment]
@2-4601 Thanks. More complicated than I thought...

**Comment by FeuRenard** [comment]
> URL in the last screenshot should be blue, not torquoise.

In contrast to the strings the link color can be fixed (just tried). I set `android:textColorLink` for light and dark theme (`themes.xml`) and this changes also the link color in this dialog. But I don't know if there are further links in Signal, that will be affected. Those in conversations remain black and white.

I will try two things over the weekend: access this link color more locally (first try already failed) and look for other affected links. Maybe this change can go into #5415 instead.

**Comment by moxie0** [comment]
in 3.19.0

**Pull request closed without merging**
