### PR TITLE
Don't connect to server if !isPushRegistered

### PR DESCRIPTION
**Pull request by paride**
Partial fix for #6620.

// FREEBIE

### CODE REVIEW

**Comment by sigenc** [comment]
THX

**Comment by paride** [comment]
@sigenc I'm not completely happy with this fix, as while it does prevent new connections to the server, it doesn't close the existing one. Unfortunately I don't see an easy way to do so. Let's see what @moxie0 thinks about it.

**Comment by sigenc** [comment]
@paride If force close the app with your commit, it cuts the existing connection and prevents a new one. Or am i wrong about this?

**Comment by paride** [comment]
@sigenc You are right, and I noticed that even if you don't force quit the connection dies anyway after some time and it's not opened again. Still it's not the best behavior.

**Comment by moxie0** [comment]
in 4.7.0

**Pull request closed without merging**
