### PR TITLE
Extend DPAD support.

### PR DESCRIPTION
**Pull request by Clam-**
Sorry for the confusion, here is my redone pull request.
(Original: #3543)

### CODE REVIEW

**Comment by Clam-** [comment]
Was just wondering if there was anything specific that needed to be done before this could be merged. I have a new device that doesn't have a touch screen and would like to continue using TextSecure.
Thanks.

**Comment by moxie0** [comment]
@Clam- sorry for the delay, if you rebase this i'll get it in

**Comment by moxie0** [comment]
Closing for lack of activity, please reopen when you have time to do the rebase. Thanks!

**Comment by Clam-** [comment]
Hi,
Sorry for the delay. I got around to doing a rebase, although this PR hasn't updated with the new changes.

What should I do now?

**Comment by McLoo** [comment]
@Clam- open a new PR

**Comment by Clam-** [comment]
Got it, will do. Thanks.

**Pull request closed without merging**
