### PR TITLE
update appcompat dependencies

### PR DESCRIPTION
**Pull request by mcginty**
* Our "betterpickers" library had an ownership chance, so I switched us to their latest version.
* Updated AppCompat to the most recent version available before the current one (which requires a compile target of Marshmallow, which in turn has a huge set of consequences).
* Start adding the new support annotations to our code

### CODE REVIEW

**Comment by moxie0** [comment]
is this necessary for one of your milestones?

**Comment by mcginty** [comment]
this is good hygiene.

**Comment by moxie0** [comment]
are the old dependencies tired?

**Comment by mcginty** [comment]
apparently, because some people can no longer build due to missing betterpickers artifacts

**Pull request closed without merging**
