### PR TITLE
Update lock notification icons

### PR DESCRIPTION
**Pull request by passy**
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Nexus 5, Android 6.0.1
- [ ] My contribution is fully baked and ready to be merged as is
- [x] I have made the choice whether I want the Bithub reward or not by omitting or adding the word `FREEBIE` in my commit message

----------

The lock icons displays in the "cached passphrase" notification currently have two issues:

- They lack high-res versions and look rather blurry on high-DPI phones.
- They have a very different shape even though they're part of the same notification. For example, one of them contains a keyhole, the other one doesn't.

Here's a proposal for unifying the look somewhat and upgrading the resolution at the same time.

<table>
<tr>
<td>

</td>
<td>

</td>
</tr>
<tr>
<td><b>Old Look</b></td>
<td><b>New Look</b></td>
</tr>
</table>

The icons I've added are the official [Material Icons](https://design.google.com/icons/) which are available under a [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) license.

What are your thoughts on this? :thought_balloon:

[Review on Reviewable](https://reviewable.io/reviews/whispersystems/signal-android/5284)

### CODE REVIEW

**Comment by agrajaghh** [comment]
how about using a filled open lock? We are using the filled one everywhere else no?

**Comment by McLoo** [comment]
Nice. None of my issues shall be unresolved for longer than a year :D #2622

**Comment by passy** [comment]
@agrajaghh Unfortunately there's no filled open lock in the design library. There's an unfilled closed one though if the two should have a consistent look. I thought it may have been deliberate to make the action look differently.

**Comment by agrajaghh** [comment]
I can create the filled one if you want to? I think it would look more consistent. @McLoo, since its your issue, what are you saying? :stuck_out_tongue_closed_eyes:

**Comment by McLoo** [comment]
Filled looks more familiar and less insubstantial/ghostly to humble me. 
Though unfilled doesn't look that bad on the bottom of the unlock screen(shot)

**Comment by agrajaghh** [comment]
since I can't attach .svg but .zip here you go:
[ic_lock_open_filled.zip](https://github.com/WhisperSystems/Signal-Android/files/144034/ic_lock_open_filled.zip)

**Comment by agrajaghh** [comment]
btw, are you sure about the sizes? size you changed the size drop 32dp to 24dp for the closed one?

**Comment by passy** [comment]
@agrajaghh That looks great! I'll change them later. I've looked at the [Google Styleguide for Icons](https://www.google.com/design/spec/style/icons.html) and their recommended size is 24dp. I couldn't find anything specific for notifications, though.

**Comment by agrajaghh** [comment]
yeah, the google docs are sometimes really bad...

Looks lke the notification icon (open lock) should be 24x24dp asset size (with 22x22dp real icon size)

For the action icon (closed lock) I just found this:
http://stackoverflow.com/questions/19454470/what-are-the-sizes-of-the-icons-in-android-notifications-action-buttons
So it  should be 32x32dp asset size (with 24x24dp real icon size)

regarding the color: the google doc says 100% #FFFFFF for the notification icon, and 54% opacity #000000 for the action icon

**Comment by passy** [comment]
@agrajaghh That's some awesome research. Thanks a lot!

I've used the [Asset Studio](https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_stat_example) to generate the PNGs from the SVG and trimmed the spacing around it. The tool also tints the icons for pre-V11 APIs.

Here's an updated screenshot:

image

**Comment by passy** [comment]
@agrajaghh 

How do you feel about this? The real size for the action icon should now be 24dp, and I've set it to a 54% opacity #000, which matches the background for the notification icon.

**Comment by agrajaghh** [comment]
closed lock, and white open are looking good! but the grey open one has a size of 16x25, was this intended?

**Comment by passy** [comment]
@agrajaghh I had trimming enabled for the icons and Android seems to make them square before displaying, but it looks a bit odd in the assets. I've changed them to be square again - without any difference in the way they're displayed, though.

**Comment by agrajaghh** [comment]
@passy still not square :stuck_out_tongue_closed_eyes:

**Comment by passy** [comment]
@agrajaghh Blimey, sorry for that. Recovering from a nasty cold, that must be the source of that sloppiness. I think I've force-pushed correctly this time.

**Comment by agrajaghh** [comment]
okay thats fixes :blush:  but `ic_menu_lock_dark` has 40dp not 32dp...

**Comment by passy** [comment]
@agrajaghh Yeah, I trusted the asset studio to generate the right padding with the actual icon size set to 24dp. I thought it looked sensible in the screenshot, but I can give it a shot with the 32/24 dimensions.

**Comment by passy** [comment]
I should have probably waited until my mental capacity gets back to normal levels, but I've tried it anyway. Asset size is now 32dp with 24dp real icon size. 54% #000. All subject to cold-induced stupidity/inaccuracy.

**Comment by passy** [comment]
I should have waited before my mental capacity is restored to normal levels, but I've tried it anyway. Here's the result with 32dp full image size, 24dp real icon size.

**Comment by agrajaghh** [comment]
currently we have in master:
- `v9/icon_cached` grey open lock 16x25dp used on gingerbread as notification icon
- `v11/icon_cached`: white open lock 24dp used on >gingerbread as notification icon

sooooo, your PR is like that:
- `ic_menu_lock_dark.png` black 54% open lock 32dp **this should be the closed one**
- `icon_cached.png` grey closed lock 24dp **this should be the open one, and in `v9/` I guess**
- `v11/icon_cached.png` white open lock 24dp **looks good**

for the size of the v9 icon I don't know. There might be a reason it was 16x25 and I couldn't find documentation about gingerbread notification icon. Maybe leave it at 16x25? Sorry for the back and forth.. what do you think?

**Comment by passy** [comment]
@agrajaghh Oh well, I've just looked at this again and I have no idea how I even ended up with that. Thanks for being so incredibly patient. I think I'll let this rest for a few days to not waste any more of your time.

**Comment by moxie0** [comment]
@passy thanks, go ahead and reopen this when you're ready

**Pull request closed without merging**
