### PR TITLE
Redesign import/export activity

### PR DESCRIPTION
**Pull request by mateoeh**
// FREEBIE

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * OnePlus 3T, Android 7.1.1
 * AVD, Android 4.4.2
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

----------

### Description

Switches the import/export activity from a card-based layout to a list-based one.

Material design spec on cards:

>When to use
>Use a card layout when displaying content that:
>
>* As a collection, comprises multiple data types, such as images, movies, and text
>* Does not require direct comparison (a user is not directly comparing images or text)
>* Supports content of highly variable length, such as comments
>* Contains interactive content, such as +1 buttons or comments
>* Would otherwise be in a grid list but needs to display more content to supplement the image

The import/export activity doesn't fit these criteria; using cards when they aren't necessary just adds extra clutter to the layout.

| Before | Light | Dark |
|--|--|--|
|io-before|io-light|io-dark|

### CODE REVIEW

**Comment by RiseT** [comment]
I support this as I that (new) layout using cards looks rather strange to me.

**Comment by Lokesh-Krishna** [comment]
Is there any reason that the text is aligned to the middle of the screen? There is just so much space left empty above. Is this something that the guidelines recommend?

**Comment by RiseT** [comment]
For consistency with the preferences view, I suggest tinting the icons blue. Not sure about the color of the strings "Import" and "Export" then. Perhaps just grey.

**Comment by mateoeh** [comment]
@Lokesh-Krishna I'm don't think the guidelines have anything to say about it one way or the other. My thought was that center alignment makes one-handed use easier, but I can change it if necessary.

**Comment by mateoeh** [comment]
@RiseT I left the icons alone in this PR, considering #6545 

I'll change the subheading tint to the primary dark color to match the preference subheadings

**Comment by mateoeh** [comment]
Here's what it looks like top-aligned with a more settings-like style. Like what you see?

io-top

**Comment by Lokesh-Krishna** [comment]
In my opinion, this does look more consistent not just with the rest of the app but also with most apps I've seen.
What do you think though?

**Comment by mateoeh** [comment]
I don't have a problem with it. Changed

**Comment by moxie0** [comment]
in 4.5.0

**Pull request closed without merging**
