### PR TITLE
Make accessibility strings in audio_view.xml translatable

### PR DESCRIPTION
**Pull request by RiseT**
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Nexus 5X, Android 7.0.0
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

----------

### Description

Related to (but doesn't entirely fix) #5908 

// FREEBIE

### CODE REVIEW

**Comment by RiseT** [comment]
Are these placed correctly within the strings.xml structure or should I put them somewhere else?

**Comment by moxie0** [comment]
they should be audio_view__audio_view_play_description etc

**Comment by RiseT** [comment]
@moxie0 

1. Rebasing on the current 3.25.0 branch seems not possible as I'm getting ```Execution failed for task ':transformClassesAndResourcesWithProguardForDebug'``` when trying to build & push to device that branch via "Run" (not when just building via "Rebuild Project")

2. Do you really mean ```audio_view__audio_view_play_description``` or rather ```audio_view__play_description```...?

3. I am aware that string names like "[...]_description" are the current "naming pattern" for accessibility strings, but let me point out that I know from the experience of translating Signal for a couple of years that most translators do not know what these strings are for (and they should, as it's important for the way these strings are translated). It would help if the string name contained "accessibility" somewhere - at least as long as the (translation) "Intructions" feature of Transifex is not being used.

**Comment by moxie0** [comment]
all i care about is that they're prefixed with the name of the xml file or the class that they're in

**Comment by RiseT** [comment]
I guess I'm done.

**Pull request closed without merging**
