### PR TITLE
fix ContactUpdates for non-e164 contacts

### PR DESCRIPTION
**Pull request by Trolldemorted**
convert every number to e164 before sending it to slaves/siblings.

### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [ ] I have tested my contribution on these devices:
 * none
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

----------

### Description

Use Util.canonalizeNumber to convert numbers to e164.

Imho we should in the long run shift to only canonalizing numbers when we are creating them the first time, and save them in e164 only.

### CODE REVIEW

**Comment by moxie0** [comment]
So this is for the Signal desktop contact cards?  What problem is non-e164 numbers causing right now?

**Comment by Trolldemorted** [comment]
As stated in #6093, Signal-Desktop becomes confused (not to mention it would be more straightforward to send and use e164 only) when receiving non-e164 contact details or blocked lists.

It was unfortunately prematurely closed when you merged the blocked lists fix.

**Comment by moxie0** [comment]
Desktop should canonicalize numbers itself, but we can do this too. The template says you haven't tested this change, though?

**Comment by Trolldemorted** [comment]
It depends on what you consider tested: I have edited an existing e164 contact to a non-e164 one and verified (with debugger attached) that the recipient was non-e164 and that the number passed to the `DeviceContact` constructor was e164 again.

But this PR also fixes `generateFullContactUpdate` which i was unable to trigger and thus unable to verify. If you tell me how i can trigger a full contact update i will gladly test it, but it should™ work.

**Comment by McLoo** [comment]
Also, if the contact  has a non e164 number, the scrubber in libpastelog fails to scrub...

**Comment by 2-4601** [comment]
> Also, if the contact has a non e164 number, the scrubber in libpastelog fails to scrub...

One example of this is probably #6276

**Pull request closed without merging**
