### PR TITLE
Use high-res callcard for TransparentContactPhoto

### PR DESCRIPTION
**Pull request by haffenloher**
Apparently I overlooked that one in #4971.

// FREEBIE

### CODE REVIEW

**Comment by moxie0** [comment]
why does this one need to be large?

**Comment by haffenloher** [comment]
it may be displayed for a short time as a loading photo when starting a Signal call from the address book. The small version looks pixelated when displayed at full screen width.

**Comment by moxie0** [comment]
but isn't this also what's displayed in the circle avatar while loading? does it still display correctly?

**Comment by haffenloher** [comment]
I think `asDrawable` is responsible for returning the circle avatars. I only changed `asCallCard` which is only used in `redphone.ui.CallCard.setPersonInfo()`.

**Pull request closed without merging**
