### PR TITLE
Make 'Tap to scan' readable in dark theme

### LINKED ISSUE #5749: Dark theme: 'Tap to scan' on new safety number verification view unreadable
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
```verify_display_fragment__tap_to_scan``` is barely readable on the dark theme (**on an actual device it's worse than on the screenshot posted below**).

### Steps to reproduce
- Switch to dark theme
- Open a conversation
- Open new safety number verification view

**Actual result:** Font color far too light for a white background
**Expected result:** Font color should be a lot darker

### Screenshots

screenshot_20161008-131746_cr_cr

### Device info

**Device:** LG Nexus 5X
**Android version:** 7.0.0
**Signal version:** 3.20.2

### PR DESCRIPTION
**Pull request by FeuRenard**
### Contributor checklist
- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Sony Xperia U, Android 4.4.4
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

----------

### Description
Fixes #5749
//FREEBIE

### Screenshots
taptoscan-dark
taptoscan-light

### CODE REVIEW

**Comment by RiseT** [comment]
Just a tiny observation: At least on my computer monitor, it looks like the font color for the safety numbers and the description are changing slightly as well in the before/after screenshots you've posted. Is this intended?

**Comment by haffenloher** [comment]
> it looks like the font color for the safety numbers and the description are changing slightly as well in the before/after screenshots for the black theme

Same for the light theme screen shots.

**Comment by RiseT** [comment]
Interestingly, the brightness of the safety numbers and the description changes in the opposite direction of the brightness of 'Tap to scan'.

**Comment by FeuRenard** [comment]
I think it's the font-weight that changes and I would blame image compression.

**Pull request closed without merging**
