### PR TITLE
Change "Forget from memory" to simply "Forget"

### PR DESCRIPTION
**Pull request by amire80**
Forgetting is usually from memory, so this makes
the message less redundant and easier to understand and to translate.

### CODE REVIEW

**Comment by mcginty** [comment]
Even the word "forget," while technically accurate, sounds kind of confusing. Really the user wants Signal to re-lock itself after some amount of time, and they likely don't care what Signal "knows" in memory.

What about "Auto-lock"?

**Comment by amire80** [comment]
Sounds OK. "Forget from memory" sounded really weird to me when I was translating. But if these strings are to be completely rewritten, it will be better if somebody who is more experienced than I am with using Signal does, because for now I am still more experienced with translating Signal than with using it.

**Comment by RiseT** [comment]
@amire80 That's simple.

**"Auto-lock Signal after some timeout interval"**
**"Amount of time to wait before auto-locking Signal"** (ditched the imho redundant "The")

By the way - you have to adjust the string names as well (i. e. that's what Moxie wants). In strings.xml as well as in all code segments that are referencing those strings.

**Comment by moxie0** [comment]
closing for lack of activity, feel free to reopen when ready

**Comment by RiseT** [comment]
@moxie0 I could do a PR with this if desired.

**Pull request closed without merging**
