### PR TITLE
Updated emoji set

### PR DESCRIPTION
**Pull request by moxie0**

### CODE REVIEW

**Comment by moxie0** [comment]
in 3.25.0

**Comment by rmueller83** [comment]
What about the new iOS 10.2 emojis? I just sent a facepalm from Signal-iOS to Android and only got garbage. (seems to be missing on Desktop, too 🤦)

**Comment by moxie0** [comment]
@rmueller83 As soon as https://github.com/iamcal/emoji-data is updated, we can update here. See https://github.com/iamcal/emoji-data/issues/69

**Comment by FeuRenard** [comment]
This PR or f747436 fixes #3555 & #3316.
Furthermore it is related to #4279 but won't fix it completely (iOS 10.2 emojis).

**Comment by rainerzufall** [comment]
@moxie0 the required repository (https://github.com/iamcal/emoji-data) is now updated! https://github.com/iamcal/emoji-data/pull/78 (which is the PR for issue https://github.com/iamcal/emoji-data/issues/77 which super seeded your required issue iamcal/emoji-data#69) was merged a few hours ago.  :tada: Therefore the update of the emojis in Signal should only depend on your miles long to do list. 

would also fix issues: https://github.com/WhisperSystems/Signal-Android/issues/4279 and https://github.com/WhisperSystems/Signal-Android/issues/6587

**Comment by moxie0** [comment]
@rainerzufall in 4.6.0 thanks

**Pull request closed without merging**
