### PR TITLE
Change notification privacy setting wording "Neither" -> "No name or message"

### LINKED ISSUE #3903: Change string 'Neither' to sth. more descriptive
It works well in the chooser, but might rise some questions when seen in the notifications preferences overview

**Display in notifications**
*Neither*

sth. like
**No/Hide Details**
or
**No/Hide Information**
would fit better imo

### PR DESCRIPTION
**Pull request by samlanning**
fixes #3903

// FREEBIE

### CODE REVIEW

**Comment by moxie0** [comment]
thanks but if you change the value, you gotta change the variable

**Comment by samlanning** [comment]
Done.

I also removed the old variables in translations in a separate commit. Not sure if you want to include this commit or not when you rebase on top of HEAD. =)

**Comment by moxie0** [comment]
right, there's never a reason to touch the translations, it can only cause problems.  you can remove that commit from the PR.

**Comment by samlanning** [comment]
done =)

**Comment by samlanning** [comment]
Is this going to be merged in? =)

**Comment by mcginty** [comment]
makes sense, especially when you see it in the summary. in 3.5.0

**Pull request closed without merging**
