### PR TITLE
Fix permission request dialog with dark theme

### LINKED ISSUE #7252: Permission request barely readable with dark theme
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The permission request for the camera is barely readable when dark theme is in use.

### Steps to reproduce
- disable camera permission
- attempt to take a picture

**Actual result:** Request text barely readable
**Expected result:** Request text easily readable

### Screenshots

screenshot_20171206-223725

### Device info

**Device:** Blackphone 2
**Android version:** 6.0.1
**Signal version:** 4.14.2

### Link to debug log

[log](https://gist.github.com/anonymous/db495ec2ad22aa80d409db17d0421988)

### PR DESCRIPTION
**Pull request by v-po**
// FREEBIE

### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Virtual device 'Nexus 5X', Android 6.0
 * Virtual device 'Pixel 2', Android 8.0.1
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
Fixes #7252

### CODE REVIEW

**Comment by moxie0** [comment]
Referencing an attribute in a drawable will result in a crash < L, but I suppose that the drawable won't be used < L. Please post before/after screen shots with theme changes, thanks!

**Comment by v-po** [comment]
Before                                |  After
:-------------------------:|:-------------------------:
api-23-before | api-23-after
api-24-before | api-24-after
api-27-before | api-27-after

Maybe set a consistent color for positive/negative buttons across api versions?

**Comment by FeuRenard** [comment]
> Maybe set a consistent color for positive/negative buttons across api versions?

If you want to adapt the colors, you can have a look at #5415.

**Comment by moxie0** [comment]
in 4.15.0

**Pull request closed without merging**
