### PR TITLE
Added 🕵&🖕 emoji

### PR DESCRIPTION
**Pull request by Pythonix**
Added 🕵&🖕 emoji

### CODE REVIEW

**Comment by art1fa** [comment]
What do you think about adding the whole new iOS 9.1 emoji set? See issue #4279. Would be great!

**Comment by Pythonix** [comment]
I want to work on that yes! But It's really painful to add all the images in photoshop and bring them to the right size. So if you know any programm that makes that easier let me know!

**Comment by art1fa** [comment]
Check [this](http://otsarag.deviantart.com/art/Complete-Emoji-Collection-555211222) out, not sure about the license though. Hope it helps!

**Comment by eosrei** [comment]
@Pythonix You can script the process with the Imagemagick `convert` and `montage` commands.

**Comment by Pythonix** [comment]
@art1fa @eosrei I started working on adding all emojis. But now I'm facing two problems and I think somebody with more knowledge has to help me...
Screenshot
The first problem is that both noses are displayed black but the first one is white.
The second problem is that with the black nose there is the color modifier displayed.
Can you give me any advice where I should start to fix that?

**Comment by art1fa** [comment]
Sorry I didn't look into this. Anyway, I think it's better to move the discussion, close this PR and create a new one once it's finished and tested 🙂 That's how OWS likes it I guess.

**Comment by Pythonix** [comment]
Just re-opened to see if @eosrei can give me any hint. We'll close it later on.

**Comment by moxie0** [comment]
Thanks @Pythonix but please only open PRs that are fully baked, fully tested, and 100% ready to be merged.

**Comment by eosrei** [comment]
@Pythonix I don't think the Android fonts support Unicode modifiers right now. "Platforms without support for emoji modifiers display a missing symbol character (box with a cross, alien, or question mark in it) next to any modified emoji." src: http://emojipedia.org/boy-emoji-modifier-fitzpatrick-type-4/ Example: 👦🏽

**Comment by Pythonix** [comment]
Yep. You're right. But whatsapp for example has its own implementation for that. That should be possible within signal too.

Date: Wed, 10 Feb 2016 01:06:28 -0800

**Pull request closed without merging**
