### PR TITLE
Move avatars to toolbar in individual convos

### LINKED ISSUE #6008: Remove Contact Pic Preceding Messages From Within Individual Conversations
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature Request
Could it be possible to remove the contact pic preceding every message (chat bubble) in a conversation in order to reduce the clutter and also make things consistent with the iOS and Desktop versions?

### Detailed Description
While the presence of contact pics before messages is helpful in group conversations (but still overwhelming when multiple messages are sent by the same person in succession as mentioned in #964), they are extremely redundant and make the screen more busy in one-to-one conversations. 
The colour of the chat bubbles is already an excellent method of distinguishing between messages. 

While doing something along the lines of other messaging apps (QKSMS, Hangouts, Facebook Messenger or Google Messenger) is what #964 sought by requesting that successive messages from the same contact be bundled, with the contact pic appearing only once for one message bundle, I am suggesting going the WhatsApp route and doing away with contact pics entirely, at least in individual conversation where they add very little, especially in excess.

Doing so would have the added benefit of making the Android app consistent with the iOS and Desktop apps where the contact pic doesn't appear within conversations. The desktop app instead displays the contact pic in the action bar which could be one alternate location for displaying the contact pic. 

Also, hopefully there should be no database issues in implementing this change like was mentioned in that other issue and that might expedite its implementation as it would be a purely UI move?

### Screenshots

Here are the iOS and desktop versions respectively:
screen322x572

unnamed

Here is how WhatsApp handles things presently:

unnamed

The contact pic is relegated to the action bar and messages bubbles only carry the name of the contact. Of course, even the name isn't present in case of individual conversations but I couldn't get a screenshot of that on the Play Store.

### PR DESCRIPTION
**Pull request by mateoeh**
// FREEBIE

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * OnePlus 3T, Android 7.1.1
 * AVDs, Android 7.1.1/Android 4.4.2
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

----------

### Description

A picture is worth a thousand words:

|Before|After|
|--|--|
|screenshot_1493258661|screenshot_1493258613|

Fixes #6008

### CODE REVIEW

**Comment by paride** [comment]
It seems to me that a lot of space is wasted between the "back" arrow and the avatar. Do we really need that arrow? The "back" (software) button does the same thing.

**Comment by RiseT** [comment]
I'm in favor of that arrow, but agree that there's a lot of space wasted between the arrow and the avatar. Is this spacing defined by some Material guideline?

**Comment by mateoeh** [comment]
Yes, the extra padding is supposed to be there to increase the touch target of the back button.

**Comment by rainerzufall** [comment]
What I personally find odd, is the extended empty space in the green bubble (to the right side of the text in the after screenshot). Is this intentional? It seems that the bubble, after removing the avatar, could display more words per line. Like the white bubble already does.

**Comment by RiseT** [comment]
@rainerzufall I guess that's because the first words of each line are too long in this example so they cannot get "unwrapped".

**Comment by paride** [comment]
@mateoeh Still, I think the spacing around the arrow is a bit odd. For example I think it would look better if the space on the right was equal to the space on the left. Even like this it could be a problem on low resolution devices. Maybe it's possible to make the arrow disappear if the avatar contact's name can't be displayed completely?

**Comment by moxie0** [comment]
Thanks but I don't want to make this change at this time. We'll revisit after some future changes are in.

**Comment by Lokesh-Krishna** [comment]
@moxie0 Could you please share what other changes are required for this to get merged so that @mateoeh or somebody else could work on them to expedite this?

**Comment by OriginalFannibal** [comment]
@moxie0 Are the changes in v4.9 (which shows up as major internal database changes on the Play Store changelog) the ones you were referring to? If so then can this be reconsidered now?

**Pull request closed without merging**
