### PR TITLE
Theme number picker text (disappearing messages)

### LINKED ISSUE #5659: Expiration times should be light on dark theme
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Dark theme inconsistency with the expiration dialog times.

### Screenshots
signal

### Device info

**Device:** Huawei U8800
**Android version:** 4.0.4
**Signal version:** 3.18.1

### PR DESCRIPTION
**Pull request by FeuRenard**
### Contributor checklist
- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Sony Xperia U, Android 4.4.4 (CyanogenMod)
 * AVD: Nexus 5X, Android 6.0
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

----------

### Description
Fixes #5659
// FREEBIE
### Screenshots
numberpicker-light
numberpicker-dark

### CODE REVIEW

**Comment by RiseT** [comment]
Button texts are blue in the dark theme. So Cancel/OK should be blue here as well (cannot remember *which* blue, though).

Rule of thumb: Whenever some text is turquoise, it is wrong. This applies to both light and dark theme.

**Comment by FeuRenard** [comment]
#5415 will fix this. I have just tested it.

**Comment by RiseT** [comment]
Ah, okay. Sorry for the false alarm.

**Comment by moxie0** [comment]
in 3.19.0

**Pull request closed without merging**
