### PR TITLE
Remove unnecessary linebreaks from res/values/strings.xml

### LINKED ISSUE #4672: A lot of translatable messages have linebreaks that seem unnecessary
A lot of translatable messages have linebreaks that seem unnecessary. As just a few examples:
* registration_progress_activity__your_device_needs_network_connectivity
* registration_progress_activity__no_network_connectivity
* registration_progress_activity__waiting_for_sms_verification
* registration_activity__your_country_code_and_phone_number

There are dozens of others.

Are these linebreaks actually useful for how the app runs, or are they there just to keep the line lengths in res/values/strings.xml under a certain limit? If it's the latter, then maybe they should be removed, because when translating in Transifex, they appear in a rather weird way, and the Transifex interface sometimes complains that they are not translated correctly, even when it appears completely artificial.

### PR DESCRIPTION
**Pull request by amire80**
fixes #4672

### CODE REVIEW

**Comment by moxie0** [comment]
My hesitation is that there's a good chance this change would require translators to re-translate all of these strings in transifex?

**Comment by amire80** [comment]
Yes, but see my comment in #4672 - it should take less than ten minutes, and if they don't do it, the current strings will just continue to work. (Unless Transifex is very silly and it deletes outdated strings. I'm not sure.)

**Comment by moxie0** [comment]
I think transifex will delete outdated strings, which is probably the correct thing for it to do.  Since a lot of the translation teams aren't as on the ball as you are, I'm going to defer on making this change.  Let's just do it incrementally as the strings themselves change.  Thanks!

**Comment by RiseT** [comment]
@moxie0 Yes, Transifex deletes outdated strings.

**Comment by amire80** [comment]
That's silly :/

Oh well.

**Comment by RiseT** [comment]
Well - to be more precise, it doesn't delete the string but the (old) translation of the string.

**Pull request closed without merging**
