### PR TITLE
Support recovering forgotten/unknown group info from sender

### PR DESCRIPTION
**Pull request by moxie0**

### CODE REVIEW

**Comment by 2-4601** [comment]
This will probably fix #1029, #1048, #2581 and #5636.

**Comment by ruppalsingh** [comment]
Is there any ETA on this?

**Comment by Trolldemorted** [comment]
this is implemented since december.

**Comment by ruppalsingh** [comment]
My bad. I confused this issue with another one.
Anyway, thanks. :)

**Comment by ruppalsingh** [comment]
That's strange.

I reset my phone a few days ago, installed Signal (Android) -- the one group I am a member of was not detected. When a group member sent a message, it was detected as "Unknown Group." I could not post from mobile, but desktop worked fine. Basically #5636. When I was re-added to the group, even though I was already in it, it started working fine.

**Comment by Trolldemorted** [comment]
Only Signal-Android and signal-cli send and respond to the group requests.

When you install Signal-Android, it has no clue about what groups you are in. If you link your old Signal-Desktop instance to your new account, it retains all group information it has had before.

Now a group member writes a message, so your Signal-Android notices that it does not know the group, and sends a group info request to all devices of the sender. If the sender has no Signal-Android or signal-cli clients online, the request is not answered.

**Pull request closed without merging**
