### PR TITLE
Color passphrase prompt text field blue

### PR DESCRIPTION
**Pull request by FeuRenard**
### First time contributor checklist
- [x] I have read [how to contribute](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)
### Contributor checklist
- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
  - Sony Xperia U, Android 4.4.4
  - AVD: Nexus 5, Android 6.0
- [x] My contribution is fully baked and ready to be merged as is
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in my commit message

---
### Description

Colors the bar below and the cursor in the text field of the passphrase prompt blue.

// FREEBIE

### CODE REVIEW

**Comment by moxie0** [comment]
Can you include before/after screenshots?

**Comment by FeuRenard** [comment]
### Screenshot
passphrase-prompt
passphrase-prompt-light
In the light theme the background color is slightly adjusted to achieve consistency among background colors.

**Comment by moxie0** [comment]
making generic changes to a theme like this seems like it could affect more than just the passphrase input edittext?

**Comment by FeuRenard** [comment]
The theme that is changed here is Light/DarkIntroTheme. This is only used by two activities: `PassphraseCreateActivity` & `PassphrasePromptActivity`. I did not figure out how to invoke the former during app usage. The latter is the screen that asks to enter the passphrase when Signal is currently locked.

I just tested with Android 4.4, 5.1 and 6.0 and this PR's colors set to green and red. I was not able to spot these colors anywhere on the screen besides the passphrase text input. Also when interacting with buttons there is no ripple color or something similar that is changed.

**Comment by moxie0** [comment]
in 3.26.0

**Pull request closed without merging**
