### PR TITLE
make invite strings plural

### LINKED ISSUE #4388: Can't properly translate some strings in Signal on Transifex
With the latest strings added to the Signal-Android project on Transifex there is no way for me to correctly translate some of them to my language (Slovenian):

SEND TO %1$s FRIEND(S)
Send %1$s SMS invite(s)?

Due to differencies between languages I can't use () keys in the cases above and if I don't use them Transifex doesn't let me save my translations.

I suggest you solve these issues the same way as you did with #2421, without using () keys.

### PR DESCRIPTION
**Pull request by agrajaghh**
fixes #4388

// FREEBIE

### CODE REVIEW

**Comment by RiseT** [comment]
@agrajaghh Nice one. I had suggested this to @mcginty as well, as I unfortunately don't know how to do this myself (wasn't aware of the mentioned issue, though). Have you looked if there are any other existing strings that one could/should pluralize?

**Comment by agrajaghh** [comment]
@RiseT nope, I didn't look for it yet. But now you know how to do it and could open a PR if you find some more :wink:

**Comment by mcginty** [comment]
moving to 3.4.0 since we're already on "string lockdown" for 3.3

**Comment by RiseT** [comment]
@agrajaghh Yep. Can do some half-educated guesses (the code pattern looks pretty clear to me), but without any Java or building knowledge I somehow worry about publishing untested code PRs...

**Comment by agrajaghh** [comment]
@RiseT if you want to learn it, the best way is to try it :blush: And setting up Android Studio to test the PR is not complicated :wink:

**Comment by moxie0** [comment]
in 3.4.0

**Pull request closed without merging**
