### PR TITLE
Unify dialog button colors

### LINKED ISSUE #5227: Button rendering colors inconsistent
There is a pretty wild **mixture of blue & turquois** (Android's standard color?) regarding the **button text color** in Signal's dialogs and the color of switches.

One of many examples would be _Settings >> Appearance >> Theme_ uses blue, vs. _Settings >> Advanced >> Signal messages and calls_ uses turquois.

**Some example info regarding the exact colors used (provided by @unrulygnu):**

_Settings >> Appearance >> Theme:_
CANCEL button render color: 1c7ac5 **[i. e. blue]**

_Settings >> Advanced >> Signal messages and calls:_
Switch render color: 1b78c1 **[i. e. some other blue]**
CANCEL / OK buttons render color: 80cbc4 **[i. e. turquois]**

**I suggest changing all of those consistently to Signal-blue (whatever that is - $1c7ac5 or $1b78c1).**

Edit: I've noticed that some of these (e. g. the CANCEL/OK buttons of Settings >> Advanced >> Signal messages and calls) only occur when using the **dark theme**.

Below are some example screenshots of dialogs still using turquois.

screenshot_20151129-122541_cr
screenshot_20151129-122645_cr
screenshot_20151129-122757_cr

### PR DESCRIPTION
**Pull request by FeuRenard**
### First time contributor checklist
- [x] I have read [how to contribute](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)
### Contributor checklist
- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
  - Sony Xperia U, Android 4.4.4
  - AVD: Nexus 5, Android 5.1
  - AVD: Nexus 5, Android 6.0
- [x] My contribution is fully baked and ready to be merged as is
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in my commit message

---
### Description

There are two types of dialogs I colored separately here:
- alert dialogs: e.g. when you attempt unregister from Signal
- (choose) dialogs: e.g. when you change the app's language

I styled the (radio) buttons for both with the same colors per theme. I chose the lighter blue for the light theme and the darker blue for the dark theme. After just setting the colors, there were some OS version specific problems with the dialogs' layout to fix:
- Marshmallow/Lollipop: height too large
- KitKat: smaller dialog with rectangle in the background (had the size of the original dialog)

I shouldn't be at all surprised if other OS versions offer further challenges :unamused:.

Fixes #5227
### Screenshots

OS order: KitKat, Lollipop, Marshmallow
alert-dark-kitkat
alert-dark-lollipop
alert-dark-marshmallow
alert-light-kitkat
alert-light-lollipop
alert-light-marshmallow
dialog-dark-kitkat
dialog-dark-lollipop
dialog-dark-marshmallow
dialog-light-kitkat
dialog-light-lollipop
dialog-light-marshmallow

### CODE REVIEW

**Comment by moxie0** [comment]
Can you include a before/after screenshot? Not sure what it is you're trying to fix up.

**Comment by FeuRenard** [comment]
Now I noticed, that the choose dialog width for 5.1 and 6.0 changes with this PR. I am going to close this PR as long this issue is not solved.
### Screenshots (2)
OS order: KitKat, Lollipop, Marshmallow
alert dialog dark
alert-dark-19
alert-dark-22
alert-dark-23

alert dialog light
alert-light-19
alert-light-22
alert-light-23

choose dialog dark
choose-dark-19
choose-dark-22
choose-dark-23

choose dialog light
choose-light-19
choose-light-22
choose-light-23

**Comment by FeuRenard** [comment]
This effect with the narrower choose dialog on Android 5.0+ seems to be dependent on the screen size. The screenshots in my first post are taken with a 4.95" AVD (Nexus 5) and are still reproducible. The more recent screenshots (before/after) originate from a 5.2" AVD (Nexus 5X).

I would accept this width change as a side effect. Partially because I don't want to mess about with the fix. It doesn't look bad, too. And I only modified the dialog height. So this seems to be an effect intended by the Android developers.

**Comment by moxie0** [comment]
The blue text in the dark dialogs (first three) feels a little out of place to me. Seems kind of hard to read.

**Comment by FeuRenard** [comment]
Android is by default using turquoise for the colour of their buttons. You can see this in some before screenshots above. The turquoise in the dark theme seems to be lighter than the turquoise in the light theme. Dark theme -> light turquoise; light theme -> dark turquoise. That's a better decision for contrast and in consequence readability. I conclude from this observation and your comment, that we should invert the use of button colour I introduced.

I did not commit the changes shown below yet.

## Screenshots
AVD Nexus 5X, Android 6.0

### dark theme
alert: dark theme, dark blue
alert-dark-lowcontrast-23
alert: dark theme, light blue <- higher contrast
alert-dark-highcontrast-23
dialog: dark theme, dark blue
dialog-dark-lowcontrast-23
dialog: dark theme, light blue <- higher contrast
dialog-dark-highcontrast-23

### light theme
alert: light theme, light blue.
alert-light-lowcontrast-23
alert: light theme, dark blue <- higher contrast
alert-light-highcontrast-23
dialog: light theme, light blue.
dialog-light-lowcontrast-23
dialog: light theme, dark blue <- higher contrast
dialog-light-highcontrast-23

**Comment by haffenloher** [comment]
On my phone's screen, the light blue looks better for both themes.

**Comment by moxie0** [comment]
i think i like light blue in dark theme and dark blue in light theme?

**Comment by FeuRenard** [comment]
I changed the button colors as requested: light blue in dark theme & dark blue in light theme.
I have tested my contribution on these devices:
  - Sony Xperia U, Android 4.4.4
  - AVD: Nexus 5X, Android 5.1
  - AVD: Nexus 5X, Android 7.1

**Comment by moxie0** [comment]
in 3.32.0

**Pull request closed without merging**
