### PR TITLE
Refuse to send push messages with empty attachments (v2)

### LINKED ISSUE #5523: Sending empty video file crashes Signal
### Bug description

Signal crashes immediately after launching
### Steps to reproduce
- get a video file with size of 0
- try to send video into group chat

**Actual result:** 
Signal crashes and it is not possible to access the app.
Reboot doesn't help
**Expected result:** 
Warning that the video is empty
### Device info

**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.16.0

### PR DESCRIPTION
**Pull request by mateoeh**
### Contributor checklist

- [X] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [X] I have tested my contribution on these devices:
  - Samsung Galaxy S5, Android 6.0.1 (CyanogenMod 13)
- [X] My contribution is fully baked and ready to be merged as is
- [X] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in my commit message

---
### Description

Don't attempt to send push messages with empty attachments - attempting to send now immediately fails instead of crashing the app.

Fixes #5523

// FREEBIE

### CODE REVIEW

**Comment by moxie0** [comment]
why don't we just make it not fail?

**Comment by mateoeh** [comment]
I assumed this check was here for a reason
[`SignalServiceAttachment.java`](https://github.com/WhisperSystems/libsignal-service-java/blob/master/java/src/main/java/org/whispersystems/signalservice/api/messages/SignalServiceAttachment.java#L70) (`libsignal-service-java`): 

```
public SignalServiceAttachmentStream build() {
  if (inputStream == null) throw new IllegalArgumentException("Must specify stream!");
  if (contentType == null) throw new IllegalArgumentException("No content type specified!");
* if (length == 0)         throw new IllegalArgumentException("No length specified!");

  return new SignalServiceAttachmentStream(inputStream, contentType, length, listener);
}
```

**Comment by moxie0** [comment]
I mean maybe we can just make it send without the attachment

**Comment by mateoeh** [comment]
Might get back to this at some point later

**Comment by Trolldemorted** [comment]
@moxie0 is silently removing the file ok? i.e. just use `continue` except throwing an exception in this PR?

**Pull request closed without merging**
