### PR TITLE
Add travis-ci configuration

### PR DESCRIPTION
**Pull request by JonasVautherin**
// FREEBIE

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * DOES NOT APPLY
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

----------

### Description

* __Scope:__ I am just adding a `.travis.yml` file and editing one line in `build.gradle`. The "WhisperSystems" account should be linked to a Travis-CI (https://travis-ci.org/) account for it to work. The integration with GitHub is quite good (I tested on my fork).
* __Risk:__ Almost inexistant. I had to change one minor line in the `build.gradle`, but that has no consequences on the code itself.
* __Notes:__ The travis configuration required a few tricks (the build was crashing because of memory issues, for instance, so the javaMaxHeapSize had to be decreased and the simulator had to be started after the build, ...). It is working right now on my fork, but I guess that will have to be checked with the other branches.

### CODE REVIEW

**Comment by JonasVautherin** [comment]
I realize it can take time to test it (I spent quite some time on it, too), but I would be interested in knowing if that is of any interest for the project.

An alternative would be to use Jenkins (I have experience with it), but it needs to be hosted somewhere.

**Comment by moxie0** [comment]
I'm not opposed to the idea, but this project started when writing tests for Android was almost impossible. Maybe that has changed, and we should reconsider the value of things like travis integration. I would kind of like to wait until we'd be getting real value from such an integration before I commit to maintaining it, though.

**Comment by JonasVautherin** [comment]
And if I may just comment on the maintenance cost: I just checked, and it is a matter of two clicks to enable/disable travis on the travis-ci.org page, once the account is linked to the repository.

If you look at [my PR on my fork](https://github.com/JonasVautherin/Signal-Android/pull/2), you'll see the integration with Travis (btw some tests are actually failing in the Signal-Android repo). So you can get an idea of the consequences of a broken CI on the repo.

**Comment by moxie0** [comment]
I'm going to close this for now

**Pull request closed without merging**
