### PR TITLE
sticky date headers

### PR DESCRIPTION
**Pull request by mcginty**

### CODE REVIEW

**Comment by McLoo** [comment]
In dark theme the date headers look to much like mini sent message bubbles, as they share the same colors.

Light theme: sent message bubbles are white with black text != date headers are grey with white text
Dark theme: sent message bubbles are grey with white text == date headers, well, the same

Besides that: :cool:

Any chance we get the fast scroll too?! Would give it twice the :cool:idity

**Comment by mcginty** [comment]
@McLoo I'd want to write a new "thumb bubble" view that's better for displaying dates, but I agree that'd be nice :).

**Comment by 2-4601** [comment]
Tested on Huawei U8800, ICS. Looking good.
I agree that the dark header bubble looks a bit too much like a message. But it floats! (in before: omg, please add option to disable the floating date bubble!)

**Comment by heyimgay** [comment]
Can someone post a screenshot with both themes?

**Comment by p4nci** [comment]
@moxie0 reproducible Signal crash when scrolling to the top in conversations with more then 500 messages:
```
--------- beginning of crash
01-25 10:26:39.082  1032  1032 E AndroidRuntime: FATAL EXCEPTION: main
01-25 10:26:39.082  1032  1032 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 1032
01-25 10:26:39.082  1032  1032 E AndroidRuntime: Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
01-25 10:26:39.082  1032  1032 E AndroidRuntime: java.lang.IllegalStateException: couldn't move cursor to position 500
01-25 10:26:39.082  1032  1032 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.CursorRecyclerViewAdapter.getCursorAtPositionOrThrow(CursorRecyclerViewAdapter.java:181)
01-25 10:26:39.082  1032  1032 E AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationAdapter.getHeaderId(ConversationAdapter.java:286)
01-25 10:26:39.082  1032  1032 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.StickyHeaderDecoration.hasHeader(StickyHeaderDecoration.java:68)
01-25 10:26:39.082  1032  1032 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.StickyHeaderDecoration.getItemOffsets(StickyHeaderDecoration.java:48)
```

**Comment by moxie0** [comment]
@p4nci please open an issue

**Pull request closed without merging**
