### PR TITLE
Fixes messages sent to self

### PR DESCRIPTION
**Pull request by Trolldemorted**
### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
  - Device A, Android X.Y.Z
  - Device B, Android Z.Y
  - Virtual device W, Android Y.Y.Z
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

---
### Description

Messages sent to self are now sent to all linked devices. Credits to gulp21 and effigies.
Fixes: #4844

// FREEBIE

I am very sorry for spamming you with notifications, but i messed up my local repository so bad that github does not allow me to open a new PR and does not notice pushes to the old one.

Nevertheless, checking for slavedevices looks like the optimal solution to me. Will test more thoroughly at work on monday, but this should do the trick.

### CODE REVIEW

**Comment by moxie0** [comment]
Hey thanks @Trolldemorted but it's going to be way more complicated than this. The self-send check is in there for necessary reasons, so disabling it will just break self-send all together. A device can't have an encrypted session with itself, it would be both Alice and Bob, but is only designed to store state for one of them.

**Comment by Trolldemorted** [comment]
@moxie0, are you really sure it is more complicated than this? This is precisely what Signal-Desktop and signal-cli are doing, and the api obviously supports this. A device can't have an encrpted session with itself, but linked Signal-Desktops/signal-clis are not the same device, after all.

I tested this PR now extensively a nexus4, a moto g, and a moto x, and it has been working flawlessly on each of them ever since. Could you have a second look?

Logs show no exceptions or anomalies, as you can see here:
http://pastebin.com/Xw5vEgP8

**Comment by moxie0** [comment]
The change would have to not send messages to your own device id, only linked device ids.

**Comment by Trolldemorted** [comment]
that is exactly what is [happening right now](https://github.com/WhisperSystems/libsignal-service-java/blob/master/java/src/main/java/org/whispersystems/signalservice/api/SignalServiceMessageSender.java#L404), isn't it?

A message to the device 1 is added to the `OutgoingPushMessageList` if and only if the recipient does not equal your local address. Should the recipient be equal to yourself, only messages to the subdevices are added.

**Comment by Trolldemorted** [comment]
@moxie0 btw, if it would open a session with itself, we should see a `MismatchedDevicesException` in the logs. I am really really sure it does not.

**Pull request closed without merging**
