### PR TITLE
Enable silent ringtone preference per recipient

### LINKED ISSUE #3957: Allow disable ringtone per conversation
Currently, it is possible to choose a different ringtone per conversation. However, it does not seem to be possible to have _no_ ringtone for a specific conversation, while having some ringtone (the system one, in my case) for all the others: The per-conversation ringtone selection lacks the "None" option.

### PR DESCRIPTION
**Pull request by cascheberg**
Fixes #3957

### CODE REVIEW

**Comment by moxie0** [comment]
i think we intentionally left out silent per-recipient ringtones in favor of mute

**Comment by cascheberg** [comment]
Mute is quite different in that it also blocks notifications and does not allow a vibration only mode. (And it's time-limited.) I see no downside in adding this option to the list, but it enables a certain use case.

**Comment by oittaa** [comment]
It's a bit annoying that you have to add ringtone with nothing in it to have "vibration only" conversations. Please consider merging this, there aren't any obvious downsides.

**Comment by cascheberg** [comment]
PR marginally improved; now `// FREEBIE`
Btw, it also fixes that "default" ringtone is not selected properly

**Comment by cascheberg** [comment]
I recently split this PR into two commits for easier review.
(This PR is one of the oldest, while it only changes a few lines.)

**Comment by moxie0** [comment]
in 3.30.0

**Pull request closed without merging**
