### PR TITLE
Improve draft saving's integration with Activity lifecycle

### LINKED ISSUE #4665: Shared media draft disappears after reboot, orphaned PersistentBlobProvider file
While working on another issue, I found a handful of orphaned files in `app_captures`, at a time when I had no draft media messages pending. I narrowed down these steps to reproduce consistently, yet there may be other ways to reproduce the issue. 

**Steps to reproduce** (UPDATED)
1. `adb shell ls -la /data/data/org.thoughtcrime.securesms/app_captures/` to verify contents
2. Select a photo or video in Gallery/Photos
3. Share the media with Signal
4. Select a contact and note the time
5. Observe the draft media message in the Conversation
6. Tap `Back` (this saves the draft media message)
7. Tap on the Conversation to open it again
8. OPTIONAL: Tap `Home` (calls `onPause()`, but not `onDestroy()`)
9. `adb reboot`, install a new build, or other `Activity`-killing action that does not call `onDestroy()`
10. Open Signal
11. Observe the draft media message in the Conversation List
12. Tap the Conversation
13. Behold the disappearance of the draft media message
14. `adb shell ls -la /data/data/org.thoughtcrime.securesms/app_captures/`
15. Behold the orphaned, a-bit-too-persistent blob file

Device info: Nexus 5, stock Android 6.0 MRA58K, Signal 3.5.0 (d21fe51), 3.5.1 (6a18824)

App state: Signal registered, SMS enabled, default SMS app

### PR DESCRIPTION
**Pull request by unrulygnu**
Fixes #4665 

Commit message is broad in case more work is needed.

### CODE REVIEW

**Comment by moxie0** [comment]
iirc there was some elaborate reason why it wasn't possible to do saveDraft in onPause. @McLoo do you remember?

**Comment by unrulygnu** [comment]
https://github.com/WhisperSystems/Signal-Android/pull/2655

**Comment by mcginty** [comment]
https://github.com/WhisperSystems/Signal-Android/pull/1985 and https://github.com/WhisperSystems/Signal-Android/pull/2266 were the two more recent changes to the placement of draft saving in the activity lifecycle, neither of the justify the placement because of any technical flaw (the first time, saveDraft was in onPause, but initializeDraft was in onCreate, so that was obviously flawed, but I don't know if we ever had a save/init in onPause/onResume).

**Comment by mcginty** [comment]
The only reason I remember it being put in onStart/onStop was performance-related. @moxie0 looks like you moved it to onDestroy from onStop in #2266.

I can't think of a good reason right now why it shouldn't be in onPause/onResume as long as we clear out whatever draft was left over in onNewIntent.

**Comment by unrulygnu** [comment]
@mcginty: 
> as long as we clear out whatever draft was left over in onNewIntent

Does the `initializeDraft()` call in the overridden `AssertedSuccessListener#onSuccess` in `onNewIntent()` satisfy this?  If not, is there something else you would prefer?

**Comment by unrulygnu** [comment]
Just rebased on current master (72064d8), no conflicts.  Please let me know if you need anything further on this PR.

**Comment by moxie0** [comment]
Sadly I'm still not comfortable moving this to onPause().  My recollection is that doing so had negative side effects.

**Pull request closed without merging**
